'use client'
/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/xUJYGiCZlOj
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import useSWR from "swr"
import DataTable from "../../../../../components/data-table"
import { CommentsColumns } from "../../../../../helper/column-table"
import LoadingScreen from "../../../../../components/LoadingScreen"

const fetcher = async (url) => {
  const res = await fetch(url);

  const data = await res.json();

  if (!res.ok) {
    const error = new Error(data.message);
    throw error;
  }

  return data;
};

export default function Page({ params: { locale } }) {
  const { data, isLoading } = useSWR(
    `/api/comments`,
    fetcher
  );

  return (
    (<div className="flex min-h-screen w-full flex-col bg-muted/40">
      {isLoading ? <LoadingScreen /> : <DataTable data={data} columns={CommentsColumns} />}
    </div>)
  );
}