/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/wdi20ytkzIM
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Archivo } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

archivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { CardContent, Card, CardTitle, CardDescription, CardHeader, CardFooter } from "../ui/card"
import { Label } from "../ui/label"
import { Input } from "../ui/input"
import { Button } from "../ui/button"
import Link from "next/link";
import { fetchCategories } from "../../data/data";

const getData = async () => {
  const res = await fetch(`${process.env.NEXTAUTH_URL}/api/categories`, {
    cache: "no-store",
  });

  if (!res.ok) {
    throw new Error("Failed");
  }

  return res.json();
};

export default async function CategoriesSection({ lang }) {
  // const Categories = await fetchCategories();
  const Categories = await getData();
  return (
    (<section className="grid grid-cols-1 md:grid-cols-2 gap-6 p-4 md:p-6">
      <div className="space-y-4 flex flex-col justify-between h-full">
        <h3 className="text-2xl font-bold">{lang == "en" ? "Categories" : "الاقسام"}</h3>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 h-full">
          {Categories.slice(0, 6).map((category, index) => {
            return (
            <Card key={index} className="h-full">
              <CardContent className="flex items-center justify-center p-6 h-full">
                <Link href={`${lang}/categories/${category.slug}?cat=${category.slug}`} className="text-xl font-semibold">{lang == 'en' ? category.title.en : category.title.ar}</Link>
              </CardContent>
            </Card>
            )
          })}
          {/* <Card className="h-full">
            <CardContent className="flex items-center justify-center p-6 h-full">
              <h3 className="text-xl font-semibold">Product Updates</h3>
            </CardContent>
          </Card>
          <Card className="h-full">
            <CardContent className="flex items-center justify-center p-6 h-full">
              <h3 className="text-xl font-semibold">Industry Insights</h3>
            </CardContent>
          </Card>
          <Card className="h-full">
            <CardContent className="flex items-center justify-center p-6 h-full">
              <h3 className="text-xl font-semibold">Company Culture</h3>
            </CardContent>
          </Card>
          <Card className="h-full">
            <CardContent className="flex items-center justify-center p-6 h-full">
              <h3 className="text-xl font-semibold">Featured Product</h3>
            </CardContent>
          </Card>
          <Card className="h-full">
            <CardContent className="flex items-center justify-center p-6 h-full">
              <h3 className="text-xl font-semibold">Featured Product</h3>
            </CardContent>
          </Card> */}
        </div>
      </div>

      <div className="space-y-4 flex flex-col justify-between h-full">
        <h3 className="text-2xl font-bold">{lang == "en" ? "Social Media" : "تواصل الاجتماعي"}</h3>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <Card>
            <CardContent className="flex items-center rounded text-[#1DA1F2] hover:bg-[#1DA1F2] hover:text-white justify-center p-6">
              <Link aria-label="twitter" href='https://twitter.com/aqraazbh'> 
                <TwitterIcon className="w-8 h-8" />
              </Link>
            </CardContent>
          </Card>
          <Card>
            <CardContent className="flex items-center rounded text-[#E1306C] hover:bg-[#E1306C] hover:text-white justify-center p-6">``
              <Link aria-label="instagram" href='https://www.instagram.com/aqrraz/'> 
                <InstagramIcon className="w-8 h-8" />
              </Link>
            </CardContent>
          </Card>
          <Card>
            <CardContent className="flex items-center rounded text-[#FF0000] hover:bg-[#FF0000] hover:text-white justify-center p-6">
                <Link aria-label="youtube" href='https://www.youtube.com/@Ezzaddin_'>
                  <YoutubeIcon className="w-8 h-8" />
                </Link>
            </CardContent>
          </Card>
          <Card>
            <CardContent className="flex items-center rounded text-[#1877F2] hover:bg-[#1877F2] hover:text-white justify-center p-6">
              <Link aria-label="facebook" href='https://www.facebook.com/profile.php?id=61555628315309'>
                <FacebookIcon className="w-8 h-8" />
              </Link>
            </CardContent>
          </Card>
        </div>
        <Card>
          <CardHeader>
            <CardTitle>{lang == "en" ? "Subscribe to our blog" : "اشترك في مدونتنا"}</CardTitle>
            <CardDescription>{lang == "en" ? "Get the latest articles delivered straight to your inbox." : "احصل على أحدث المقالات التي يتم إرسالها إلى بريدك الإلكتروني."}</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="space-y-2">
              <Label htmlFor="email">{lang == "en" ? "Email address" : "عنوان البريد الإلكتروني"}</Label>
              <Input id="email" placeholder="m@example.com" type="email" />
            </div>
          </CardContent>
          <CardFooter>
            <Button className="w-full" type="submit">
              {lang == "en" ? "Subscribe" : "أشتراك"}
            </Button>
          </CardFooter>
        </Card>
      </div>
    </section>)
  );
}

function FacebookIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z" />
    </svg>)
  );
}


function InstagramIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <rect width="20" height="20" x="2" y="2" rx="5" ry="5" />
      <path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z" />
      <line x1="17.5" x2="17.51" y1="6.5" y2="6.5" />
    </svg>)
  );
}


function TwitterIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z" />
    </svg>)
  );
}


function YoutubeIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M2.5 17a24.12 24.12 0 0 1 0-10 2 2 0 0 1 1.4-1.4 49.56 49.56 0 0 1 16.2 0A2 2 0 0 1 21.5 7a24.12 24.12 0 0 1 0 10 2 2 0 0 1-1.4 1.4 49.55 49.55 0 0 1-16.2 0A2 2 0 0 1 2.5 17" />
      <path d="m10 15 5-3-5-3z" />
    </svg>)
  );
}