/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/bDPeo60bChf
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

import Link from "next/link";
import Image from "next/image";
import { format, parseISO } from "date-fns";

const formatDate = (isoDateString) => {
  const date = parseISO(isoDateString);
  return format(date, 'MMMM d, yyyy');
};


export default async function FeaturedArticle({ lang, posts }) {
  // const article = await fetchPost();
  return (
    (<section className="relative overflow-hidden rounded-lg bg-cover bg-center bg-no-repeat py-24 md:py-32 lg:py-40">
      <div className="absolute inset-0 bg-gradient-to-r from-gray-950/80 to-gray-950/80" />
      <div className="relative z-10 container mx-auto px-4 md:px-6">
        <div className="flex flex-wrap items-center justify-between gap-4 mb-8">
          <Link href={`${lang}/categories/${posts.cat.slug}`} className="rounded-full first:bg-gray-200 first:text-gray-900 first:dark:bg-gray-800 first:dark:text-gray-400 bg-primary px-4 py-1 text-xs font-medium text-white">
            {lang == 'en' ? posts.cat.title.en : posts.cat.title.ar}
          </Link>
          <p className="text-sm text-gray-400">{formatDate(posts.createdAt)}</p>
        </div>
        <div className="max-w-3xl">
          <Link href={`${lang}/post/${posts.slug}`} className="text-3xl font-bold tracking-tight text-white md:text-4xl lg:text-5xl">
            {lang == 'en' ? posts.title.en : posts.title.ar}
          </Link>
          <p className="mt-4 line-clamp-4 md:line-clamp-none text-lg leading-relaxed text-gray-300">
            {lang == 'en' ? posts.desc.en : posts.desc.ar}
          </p>
        </div>
      </div>
      <Image src={posts.img} width={1280} height={720} alt={posts.title.en} className={`absolute inset-0 -z-10 h-full w-full aspect-video`} />
    </section>)
  );
}